{
 "title": "DSI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 1, "w": 2, "x": 22, "y": 0 },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "title": "Device 1 ",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "title": "Current Sensor (1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT current_sensor_1 FROM slt_sensor_data.sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Current Sensor (2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT current_sensor_2 FROM slt_sensor_data.sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "IR Temp Sensor ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT ir_temp FROM slt_sensor_data.sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "K Type Temp Sensor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT k_type_temp FROM slt_sensor_data.sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Device 2",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "title": "Current Sensor (1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT current_sensor_1 FROM slt_sensor_data.device2_sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Current Sensor (2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT current_sensor_2 FROM slt_sensor_data.device2_sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "IR Temp Sensor ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT ir_temp FROM slt_sensor_data.device2_sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "K Type Temp Sensor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT k_type_temp FROM slt_sensor_data.device2_sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Device 3",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "title": "Current Sensor (1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT current_sensor_1 FROM slt_sensor_data.device3_sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Current Sensor (2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT current_sensor_2 FROM slt_sensor_data.device3_sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "IR Temp Sensor ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT ir_temp FROM slt_sensor_data.device3_sensor_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "K Type Temp Sensor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "slt_sensor_data",
     "rawSql": "SELECT k_type_temp FROM slt_sensor_data.device3_sensor_data LIMIT 50 "
    }
   ]
  }
 ]
}