{
 "title": "Automated Sensor Dashboard - DSI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Device 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"IR_Sensor_1\") AS \"IR Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"K_Type_Sensor_1\") AS \"K Type Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Miller_1\") AS \"Current Miller Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Mixer_1\") AS \"Current Mixer Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' AND time > now() - 1h"
    }
   ]
  },
  {
   "title": "Device 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"IR_Sensor_2\") AS \"IR Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"K_Type_Sensor_2\") AS \"K Type Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Miller_2\") AS \"Current Miller Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Mixer_2\") AS \"Current Mixer Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' AND time > now() - 1h"
    }
   ]
  },
  {
   "title": "Device 3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"IR_Sensor_3\") AS \"IR Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"K_Type_Sensor_3\") AS \"K Type Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Miller_3\") AS \"Current Miller Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' AND time > now() - 1h"
    },
    {
     "query": "SELECT last(\"Current_Mixer_3\") AS \"Current Mixer Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' AND time > now() - 1h"
    }
   ]
  },
  {
   "title": "WI-FI",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "median",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    { "topic": "test/topic" }
   ]
  },
  {
   "title": "Bluetooth",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "median",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    { "topic": "test/topic" }
   ]
  },
  {
   "title": "IR sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"IR_Sensor_1\") AS \"IR Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' GROUP BY time(10s)"
    },
    {
     "query": "SELECT mean(\"IR_Sensor_2\") AS \"IR Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' GROUP BY time(10s)"
    },
    {
     "query": "SELECT mean(\"IR_Sensor_3\") AS \"IR Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' GROUP BY time(10s)"
    }
   ]
  },
  {
   "title": "K type sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "\nSELECT last(\"K_Type_Sensor_1\") AS \"K Type Sensor 01\" FROM \"sensor_data\" WHERE \"device\" = '1' GROUP BY time(10s)"
    },
    {
     "query": "SELECT last(\"K_Type_Sensor_2\") AS \"K Type Sensor 02\" FROM \"sensor_data\" WHERE \"device\" = '2' GROUP BY time(10s)"
    },
    {
     "query": "SELECT last(\"K_Type_Sensor_3\") AS \"K Type Sensor 03\" FROM \"sensor_data\" WHERE \"device\" = '3' GROUP BY time(10s)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {}
   ]
  }
 ]
}